[context.production.environment]
  REACT_APP_API_URL = "https://api.infrarays.digitalungdom.se"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://devapi.infrarays.digitalungdom.se"

[context.branch-deploy.environment]
  REACT_APP_API_URL = "https://devapi.infrarays.digitalungdom.se"

[context.dev.environment]
  REACT_APP_API_URL = "https://devapi.infrarays.digitalungdom.se"

[build]
  NETLIFY_USE_YARN = "true"
  environment = { YARN_VERSION = "1.22.17", NODE_VERSION = "16.13.1" }
  command = "yarn run build"
  publish = ".next/"
